networks:
  auth:
    name: auth
    driver: bridge

volumes:
  database-1:
    name: auth-database-1
  database-2:
    name: auth-database-2
  database-3:
    name: auth-database-3
  cache:
    name: auth-cache

x-db-common: &db-common
  image: "cockroachdb/cockroach:latest-v26.2"
  restart: always
  networks:
    auth:

services:
  database-1:
    <<: *db-common
    container_name: auth-database-1
    command: start --certs-dir=certs --listen-addr=auth-database-1:26357 --sql-addr=auth-database-1:26257 --join=auth-database-1:26357,auth-database-2:26357,auth-database-3:26357
    volumes:
      - database-1:/cockroach/cockroach-data
      - ./cockroach/certs:/cockroach/certs:ro

  database-2:
    <<: *db-common
    container_name: auth-database-2
    command: start --certs-dir=certs --listen-addr=auth-database-2:26357 --sql-addr=auth-database-2:26257 --join=auth-database-1:26357,auth-database-2:26357,auth-database-3:26357
    volumes:
      - database-2:/cockroach/cockroach-data
      - ./cockroach/certs:/cockroach/certs:ro
    depends_on:
      database-1:
        condition: service_started

  database-3:
    <<: *db-common
    container_name: auth-database-3
    command: start --certs-dir=certs --listen-addr=auth-database-3:26357 --sql-addr=auth-database-3:26257 --join=auth-database-1:26357,auth-database-2:26357,auth-database-3:26357
    volumes:
      - database-3:/cockroach/cockroach-data
      - ./cockroach/certs:/cockroach/certs:ro
    depends_on:
      database-2:
        condition: service_started

  init-cluster:
    image: "cockroachdb/cockroach:latest-v26.2"
    container_name: auth-database-init
    command: init --certs-dir=certs
    networks:
      auth:
    volumes:
      - ./cockroach/certs:/cockroach/certs:ro
    depends_on:
      database-1:
        condition: service_started
    environment:
      COCKROACH_HOST: auth-database-1:26357

  migrate-cluster:
    image: "cockroachdb/cockroach:latest-v26.2"
    container_name: auth-database-migrate
    command: sql --certs-dir=certs --file "/cockroach/migrations.sql"
    networks:
      auth:
    volumes:
      - ./cockroach/certs:/cockroach/certs:ro
      - ./cockroach/migrations.sql:/cockroach/migrations.sql:ro
    depends_on:
      database-1:
        condition: service_started
    environment:
      COCKROACH_HOST: auth-database-1:26257

  seed-cluster:
    image: "cockroachdb/cockroach:latest-v26.2"
    container_name: auth-database-seed
    command: sql --certs-dir=certs --file "/cockroach/seeding.sql"
    networks:
      auth:
    volumes:
      - ./cockroach/certs:/cockroach/certs:ro
      - ./cockroach/seeding.sql:/cockroach/seeding.sql:ro
    depends_on:
      database-1:
        condition: service_started
      migrate-cluster:
        condition: service_completed_successfully
    environment:
      COCKROACH_HOST: auth-database-1:26257

  cache:
    image: valkey/valkey:9.1-alpine
    container_name: auth-cache
    entrypoint: valkey-server --appendonly yes --save 60 1
    networks:
      auth:
    healthcheck:
      test: ["CMD", "valkey-cli", "-h", "127.0.0.1", "-p", "6379", "PING"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - cache:/data

  api:
    image: ghcr.io/botprzemek/auth/api:latest
    build: ./api
    container_name: auth-api
    networks:
      auth:
    volumes:
      - ./cockroach/certs:/certs:ro
    depends_on:
      cache:
        condition: service_started
    environment:
      API_SERVER_HOST: 0.0.0.0
      API_SERVER_PORT: 3000

      API_TOKEN_ISSUER: auth
      API_TOKEN_SECRET: your-secret

      API_DATABASE_HOST: auth-database-1
      API_DATABASE_PORT: 26257
      API_DATABASE_NAME: dev
      API_DATABASE_USERNAME: dev
      API_DATABASE_PASSWORD: your-password

      API_CACHE_HOST: auth-cache
      API_CACHE_PORT: 6379

  app:
    image: ghcr.io/botprzemek/auth/app:latest
    build: ./app
    container_name: auth-app
    networks:
      auth:
    depends_on:
      api:
        condition: service_started
    environment:
      NITRO_HOST: 0.0.0.0
      NITRO_PORT: 3001

      NUXT_APP_BASE_URL: /
      NUXT_PUBLIC_API_URL: http://localhost:3000
