name: basketball

include:
  - ./api/compose.yaml
  - ./cache/compose.yaml
  - ./database/compose.yaml
  - ./panel/compose.yaml

networks:
  default:
    name: basketball
  database:
    name: basketball-database
  gateway:
    name: basketball-gateway