global:
  namespace: auth

database:
  replicas: 3
  image: "cockroachdb/cockroach:latest-v26.2"
  storageSize: 10Gi
  credentials:
    database: "dev"
    username: "dev"
    password: "your-password"

cache:
  image: "valkey/valkey:9.0-alpine"
  replicas: 6
  storageSize: 2Gi

api:
  replicas: 3
  image: "auth/api:0.1.0"
  port: 3000
  token:
    issuer: "auth"
    secret: "your-secret"

app:
  replicas: 3
  image: "auth/app:0.1.0"
  port: 3001