services:
  database-1:
    restart: always
    image: "cockroachdb/cockroach:latest"
    networks:
      - database
    container_name: basketball-database-1
    volumes:
      - type: volume
        source: database-1
        target: /cockroach/cockroach-data
        volume:
          nocopy: true
      - type: bind
        source: ./src/initialize.sh
        target: /cockroach/initialize.sh
    command: bash ./initialize.sh database-1

  database-2:
    restart: always
    image: "cockroachdb/cockroach:latest"
    networks:
      - database
    container_name: basketball-database-2
    volumes:
      - type: volume
        source: database-2
        target: /cockroach/cockroach-data
        volume:
          nocopy: true
      - type: bind
        source: ./src/initialize.sh
        target: /cockroach/initialize.sh
    command: bash ./initialize.sh database-2
    depends_on:
      - database-1

  database-3:
    restart: always
    image: "cockroachdb/cockroach:latest"
    networks:
      - database
    container_name: basketball-database-3
    volumes:
      - type: volume
        source: database-3
        target: /cockroach/cockroach-data
        volume:
          nocopy: true
      - type: bind
        source: ./src/initialize.sh
        target: /cockroach/initialize.sh
    command: bash ./initialize.sh database-3
    depends_on:
      - database-1

volumes:
  database-1:
    name: basketball-database-1
  database-2:
    name: basketball-database-2
  database-3:
    name: basketball-database-3

networks:
  database:
    name: basketball-database