networks:
  basketball:
    external: true

services:
  devcontainer:
    image: basketball/devcontainer:0.1.0
    build: ./.devcontainer
    container_name: basketball-devcontainer
    networks:
      basketball:
        aliases:
          - api
          - app
    volumes:
      - .:/workspace/basketball:cached
      - ./.devcontainer/nginx/conf.d:/etc/nginx/conf.d:cached
    tty: true
    stdin_open: true
    command: /bin/bash
    environment:
      API_SERVER_HOST: 0.0.0.0
      API_SERVER_PORT: 3000

      API_DATABASE_HOST: basketball-database-1
      API_DATABASE_PORT: 26257
      API_DATABASE_NAME: dev

      API_CACHE_HOST: basketball-cache
      API_CACHE_PORT: 6379
