apiVersion: v1
kind: Service
metadata:
  name: auth-app
spec:
  ports:
    - port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}
  selector:
    app: auth-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-app
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: auth-app
  template:
    metadata:
      labels:
        app: auth-app
    spec:
      initContainers:
        - name: wait-for-api
          image: groundnuty/k8s-wait-for:v2.0
          args: ["service", "auth-api"]
      containers:
        - name: app
          image: {{ .Values.app.image }}
          ports:
            - containerPort: {{ .Values.app.port }}
          env:
            - name: NITRO_HOST
              value: "0.0.0.0"
            - name: NITRO_PORT
              value: {{ .Values.app.port | quote }}
            - name: NUXT_APP_BASE_URL
              value: "/"
            - name: NUXT_API_URL
              value: "http://auth-api:3000/"