# auth-chart/templates/database.yaml
apiVersion: v1
kind: Service
metadata:
  name: auth-database
  labels:
    app: auth-database
spec:
  ports:
    - port: 26257
      name: sql
    - port: 8080
      name: http
  clusterIP: None
  selector:
    app: auth-database
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auth-database
spec:
  serviceName: "auth-database"
  replicas: { { .Values.database.replicas } }
  selector:
    matchLabels:
      app: auth-database
  template:
    metadata:
      labels:
        app: auth-database
    spec:
      containers:
        - name: cockroachdb
          image: { { .Values.database.image } }
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 26257
              name: sql
            - containerPort: 8080
              name: http
          # Automatyczne generowanie flagi --join dla wszystkich replik na bazie wielkości klastra z values.yaml
          command:
            - "sh"
            - "-c"
            - |
              /cockroach/cockroach start --insecure \
              --http-addr=0.0.0.0:8080 \
              --listen-addr=0.0.0.0:26357 \
              --sql-addr=0.0.0.0:26257 \
              --advertise-addr=$(hostname).auth-database \
              --join=auth-database-0.auth-database:26357,auth-database-1.auth-database:26357,auth-database-2.auth-database:26357
          volumeMounts:
            - name: datadir
              mountPath: /cockroach/cockroach-data
  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: { { .Values.database.storageSize } }
