apiVersion: v1
kind: ConfigMap
metadata:
  name: database-sql-scripts
data:
  migrations.sql: |
    CREATE SCHEMA IF NOT EXISTS auth;
  seeding.sql: |
    SELECT 1;
---
apiVersion: batch/v1
kind: Job
metadata:
  name: auth-database-bootstrap
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: cluster-init
          image: {{ .Values.database.image }}
          command:
            [
              "/cockroach/cockroach",
              "init",
              "--insecure",
              "--host=auth-database-0.auth-database:26357",
            ]
        - name: cluster-migrate
          image: {{ .Values.database.image }}
          command:
            [
              "sh",
              "-c",
              "/cockroach/cockroach sql --insecure --host=auth-database-0.auth-database:26257 --file=/scripts/migrations.sql",
            ]
          volumeMounts:
            - name: sql-volume
              mountPath: /scripts
      containers:
        - name: cluster-seed
          image: {{ .Values.database.image }}
          command:
            [
              "sh",
              "-c",
              "/cockroach/cockroach sql --insecure --host=auth-database-0.auth-database:26257 --file=/scripts/seeding.sql",
            ]
          volumeMounts:
            - name: sql-volume
              mountPath: /scripts
      volumes:
        - name: sql-volume
          configMap:
            name: database-sql-scripts
---
apiVersion: batch/v1
kind: Job
metadata:
  name: auth-cache-bootstrap
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: cluster-creator
          image: {{ .Values.cache.image }}
          command:
            - "sh"
            - "-c"
            - |
              echo "Czekam aż pody Valkey będą gotowe..."
              until nc -z auth-cache-5.auth-cache-headless 6379; do
                sleep 2
              done

              echo "Pody wstały. Pobieram IP wszystkich podów..."
              IPS=""
              for i in 0 1 2 3 4 5; do
                IP=$(getent hosts auth-cache-$i.auth-cache-headless | awk '{ print $1 }')
                IPS="$IPS $IP:6379"
              done

              echo "Uruchamiam tworzenie klastra z IP: $IPS"
              echo "yes" | valkey-cli --cluster create $IPS --cluster-replicas 1