services:
  api:
    restart: always
    networks:
      - cache
      - database
      - gateway
    image: "basketball-api:latest"
    container_name: basketball-api
    build: .
    develop:
      watch:
        - action: rebuild
          path: /src