name: Scan for leaked credentials

on:
  push:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.94.0
        with:
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --exclude-paths=./cockroach
